### ISSUE TITLE
Error while mounting trustee plugin in Vault v1.4.2

### ISSUE THREAD

**Issue by banandh** [immutability-io/trustee#1]
Hi,

i downloed this plugin under /opt/vault-plugins/trustee path and as mentioned i have specified the same in config.json of the start server config file.

calculated SHA of this folder using below comment
 (comment mentioned in the blob "shasum -a 256 "$HOME/etc/vault.d/vault_plugins/trustee" | cut -d' ' -f1" - didnt work in ubuntu linux)

find /opt/vault-plugins/trustee -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum  -  "8fbc734261c43c1bde4800ae289040e9760ea56a -"

when i run vault secrets enable -path=immutability/sandbox/trust -plugin-name=trustee plugin command i get below error 

**Client CLI:**
POST http://127.0.0.1:23300/v1/sys/mounts/immutability/sandbox/trust
Code: 400. Errors:

* error verifying checksum: read /opt/vault-plugins/trustee: is a directory

**Server**

2020-07-30T18:48:43.448+0530 [ERROR] secrets.system.system_010e452e: error occurred during enable mount: path=immutability/sandbox/trust/ error="plugin not found in the catalog: trustee"
2020-07-30T18:50:24.722+0530 [ERROR] secrets.system.system_010e452e: error occurred during enable mount: path=immutability/sandbox/trust/ error="error verifying checksum: read /opt/vault-plugins/trustee: is a directory"

**Comment by cypherhat** [comment]
A couple points:

1. The SHASUM should be the value contained in the `SHA256SUM` file that came with the plugin.
2. Your error indicates that `/opt/vault-plugins/trustee` is not the plugin file but rather a directory.

You may have created a directory called `/opt/vault-plugins/trustee` and put the plugin under that: `/opt/vault-plugins/trustee/trustee`

**Comment by banandh** [comment]
1.The SHASUM should be the value contained in the SHA256SUM file that came with the plugin. - I dont get What you mean
2. Your error indicates that /opt/vault-plugins/trustee is not the plugin file but rather a directory - So you mean , i can make the plugin directory as /opt/vault-plugins in server config file. Is that right??

**Comment by cypherhat** [comment]
You should review the documentation/learning at https://www.vaultproject.io/
